# Adaptive configuration for REGRESSION_DLNS
# Inherits from adaptive_config.yaml and adds model-specific settings

# Import base adaptive settings
__BASE__: adaptive_config.yaml

# Model-specific settings
MODEL_TYPE: "regression_dlns"

# Override any model-specific parameters here

REGRESSION_DLNS:
  HIDDEN_DIM: 256
  NUM_LAYERS: 6
  DROPOUT: 0.1
