# Regression DLNs specific configuration
# Inherits from adaptive_config.yaml

# Import base adaptive settings
__BASE__: adaptive_config.yaml

MODEL:
  TYPE: "regression_dlns"
  REGRESSION_DLNS:
    N_LOGIC_LAYERS: 2
    NEURONS_PER_LAYER: [32, 16]
    TEMPERATURE: 0.5
    N_THRESHOLDS: 3
    USE_RESIDUAL: true

# DLNs training settings - they can be harder to train
TRAINING:
  LEARNING_RATE: 0.001
  BATCH_SIZE: 64  # Smaller batch size for stability
  NUM_EPOCHS: 150
  WEIGHT_DECAY: 0.00001
  GRAD_CLIP_NORM: 0.5
  LR_SCHEDULER:
    TYPE: "step"
    STEP_SIZE: 50
    GAMMA: 0.5