# Adaptive configuration for SAINT_S
# Inherits from adaptive_config.yaml and adds model-specific settings

# Import base adaptive settings
__BASE__: adaptive_config.yaml

# Model-specific settings
MODEL_TYPE: "saint_s"

# Override any model-specific parameters here

SAINT_S:
  NUM_LAYERS: 4
  DIM: 128
  NUM_HEADS: 8
  DROPOUT: 0.05
