# Size-aware configuration for symmetric adaptive conformal prediction
# Targets: Small objects 90%, Medium 89%, Large 85%

# Training parameters
learning_rate: 0.001
epochs: 100
batch_size: 256
early_stopping_patience: 15

# Model architecture
hidden_dims: [256, 128, 64]  # Deeper network for size-aware adaptation
dropout_rate: 0.1
activation: elu
use_batch_norm: true

# Size-aware loss function
use_size_aware_loss: true
small_target_coverage: 0.90   # Target 90% for small objects
medium_target_coverage: 0.89  # Target 89% for medium objects  
large_target_coverage: 0.85   # Target 85% for large objects
lambda_efficiency: 0.40       # Higher weight to push down large object MPIW
coverage_loss_type: smooth_l1
size_normalization: true

# Size thresholds (based on sqrt of area)
small_threshold: 32.0   # Objects smaller than 32x32
large_threshold: 96.0   # Objects larger than 96x96

# Calibration
target_coverage: 0.89   # Overall target (for tau calibration)
tau_smoothing: 0.6
min_tau: 0.05          # Allow very tight intervals
max_tau: 3.0

# Optimization
lr_scheduler: cosine
min_lr: 0.0000001
weight_decay: 0.0001
grad_clip_norm: 1.0
warmup_epochs: 3

# Data augmentation
augment_calibration: false

# Reproducibility
seed: 42