# Adaptive configuration for T2G_FORMER
# Inherits from adaptive_config.yaml and adds model-specific settings

# Import base adaptive settings
__BASE__: adaptive_config.yaml

# Model-specific settings
MODEL_TYPE: "t2g_former"

# Override any model-specific parameters here

TRANSFORMER:
  NUM_LAYERS: 4
  DIM: 128
  NUM_HEADS: 8
  DROPOUT: 0.05
  ATTENTION_DROPOUT: 0.05
