# T2G-Former specific configuration
# Inherits from adaptive_config.yaml

# Import base adaptive settings
__BASE__: adaptive_config.yaml

MODEL:
  TYPE: "t2g_former"
  T2G_FORMER:
    D_MODEL: 64
    N_HEADS: 4
    N_LAYERS: 2
    GRAPH_HIDDEN: 32
    DROPOUT: 0.1
    GRAPH_SPARSITY: 0.3

# T2G-Former training settings
TRAINING:
  LEARNING_RATE: 0.0005
  BATCH_SIZE: 128
  NUM_EPOCHS: 120
  WEIGHT_DECAY: 0.00001
  GRAD_CLIP_NORM: 0.5  # Graph models can have gradient issues