# Adaptive configuration for TABM
# Inherits from adaptive_config.yaml and adds model-specific settings

# Import base adaptive settings
__BASE__: adaptive_config.yaml

# Model-specific settings
MODEL_TYPE: "tabm"

# Override any model-specific parameters here

TABM:
  NUM_BLOCKS: 4  # More blocks for complex patterns
  DIM: 128
  DROPOUT: 0.05
